### ISSUE TITLE
Followed the install wrapper instruction, can't install on Windows.

### ISSUE THREAD

**Issue by minhlong94** [Borda/pyGCO#17]
And seems like the error I have is because of pybind11. The error is `AssertionError: nothing found: []`

**Comment by Borda** [comment]
can you share the full trace and how to reproduce it?

**Comment by minhlong94** [comment]
So I share the full reproduce code here:
```bash
E:\Code>git clone https://github.com/Borda/pyGCO
Cloning into 'pyGCO'...
remote: Enumerating objects: 440, done.
remote: Counting objects: 100% (131/131), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 440 (delta 59), reused 104 (delta 41), pack-reused 309R
Receiving objects: 100% (440/440), 1.34 MiB | 6.19 MiB/s, done.
Resolving deltas: 100% (213/213), done.

E:\Code>cd pyGCO

E:\Code\pyGCO>pip install -r requirements.txt
Collecting Cython>=0.23.1
  Downloading Cython-0.29.23-cp38-cp38-win_amd64.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 2.2 MB/s
Requirement already satisfied: numpy>=1.8.2 in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 2)) (1.20.3)
Collecting matplotlib>=1.3.1
  Using cached matplotlib-3.4.2-cp38-cp38-win_amd64.whl (7.1 MB)
Collecting urllib3
  Using cached urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Requirement already satisfied: pillow>=6.2.0 in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages (from matplotlib>=1.3.1->-r requirements.txt (line 3)) (8.2.0)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp38-cp38-win_amd64.whl (51 kB)
Requirement already satisfied: six in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages (from cycler>=0.10->matplotlib>=1.3.1->-r requirements.txt (line 3)) (1.16.0)
Installing collected packages: python-dateutil, pyparsing, kiwisolver, cycler, urllib3, matplotlib, Cython
Successfully installed Cython-0.29.23 cycler-0.10.0 kiwisolver-1.3.1 matplotlib-3.4.2 pyparsing-2.4.7 python-dateutil-2.8.1 urllib3-1.26.4

E:\Code\pyGCO>python setup.py install
running install
running bdist_egg
running egg_info
creating gco_wrapper.egg-info
writing gco_wrapper.egg-info\PKG-INFO
writing dependency_links to gco_wrapper.egg-info\dependency_links.txt
writing requirements to gco_wrapper.egg-info\requires.txt
writing top-level names to gco_wrapper.egg-info\top_level.txt
writing manifest file 'gco_wrapper.egg-info\SOURCES.txt'
reading manifest file 'gco_wrapper.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'test_*.py'
warning: no previously-included files found matching 'test_*.cpp'
warning: no previously-included files found matching '*.yml'
warning: no previously-included files found matching 'Makefile'
no previously-included directories found matching 'images'
no previously-included directories found matching 'gco_source\matlab'
writing manifest file 'gco_wrapper.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.8
creating build\lib.win-amd64-3.8\gco
copying gco\cgco.py -> build\lib.win-amd64-3.8\gco
copying gco\pygco.py -> build\lib.win-amd64-3.8\gco
copying gco\__init__.py -> build\lib.win-amd64-3.8\gco
copying gco\cgco.cpp -> build\lib.win-amd64-3.8\gco
copying gco\cgco.h -> build\lib.win-amd64-3.8\gco
running build_ext
building 'gco.libcgco' extension
creating build\temp.win-amd64-3.8
creating build\temp.win-amd64-3.8\Release
creating build\temp.win-amd64-3.8\Release\gco_source
creating build\temp.win-amd64-3.8\Release\gco
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Igco_source -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\include -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\include -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include" "-ID:\Windows Kits\10\include\10.0.19041.0\ucrt" "-ID:\Windows Kits\10\include\10.0.19041.0\shared" "-ID:\Windows Kits\10\include\10.0.19041.0\um" "-ID:\Windows Kits\10\include\10.0.19041.0\winrt" "-ID:\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tpgco_source\graph.cpp /Fobuild\temp.win-amd64-3.8\Release\gco_source\graph.obj
graph.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Igco_source -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\include -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\include -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include" "-ID:\Windows Kits\10\include\10.0.19041.0\ucrt" "-ID:\Windows Kits\10\include\10.0.19041.0\shared" "-ID:\Windows Kits\10\include\10.0.19041.0\um" "-ID:\Windows Kits\10\include\10.0.19041.0\winrt" "-ID:\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tpgco_source\maxflow.cpp /Fobuild\temp.win-amd64-3.8\Release\gco_source\maxflow.obj
maxflow.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Igco_source -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\include -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\include -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include" "-ID:\Windows Kits\10\include\10.0.19041.0\ucrt" "-ID:\Windows Kits\10\include\10.0.19041.0\shared" "-ID:\Windows Kits\10\include\10.0.19041.0\um" "-ID:\Windows Kits\10\include\10.0.19041.0\winrt" "-ID:\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tpgco_source\LinkedBlockList.cpp /Fobuild\temp.win-amd64-3.8\Release\gco_source\LinkedBlockList.obj
LinkedBlockList.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Igco_source -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\include -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\include -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include" "-ID:\Windows Kits\10\include\10.0.19041.0\ucrt" "-ID:\Windows Kits\10\include\10.0.19041.0\shared" "-ID:\Windows Kits\10\include\10.0.19041.0\um" "-ID:\Windows Kits\10\include\10.0.19041.0\winrt" "-ID:\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tpgco_source\GCoptimization.cpp /Fobuild\temp.win-amd64-3.8\Release\gco_source\GCoptimization.obj
GCoptimization.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Igco_source -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\include -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\include -IC:\Users\marcu\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include" "-ID:\Windows Kits\10\include\10.0.19041.0\ucrt" "-ID:\Windows Kits\10\include\10.0.19041.0\shared" "-ID:\Windows Kits\10\include\10.0.19041.0\um" "-ID:\Windows Kits\10\include\10.0.19041.0\winrt" "-ID:\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tpgco\cgco.cpp /Fobuild\temp.win-amd64-3.8\Release\gco\cgco.obj
cgco.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:gco_source /LIBPATH:C:\Users\marcu\AppData\Local\Programs\Python\Python38\libs /LIBPATH:C:\Users\marcu\AppData\Local\Programs\Python\Python38\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\lib\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.19041.0\um\x64" build\temp.win-amd64-3.8\Release\gco_source\graph.obj build\temp.win-amd64-3.8\Release\gco_source\maxflow.obj build\temp.win-amd64-3.8\Release\gco_source\LinkedBlockList.obj build\temp.win-amd64-3.8\Release\gco_source\GCoptimization.obj build\temp.win-amd64-3.8\Release\gco\cgco.obj /OUT:build\lib.win-amd64-3.8\gco\libcgco.cp38-win_amd64.pyd
   Creating library build\lib.win-amd64-3.8\gco\libcgco.cp38-win_amd64.lib and object build\lib.win-amd64-3.8\gco\libcgco.cp38-win_amd64.exp
Generating code
Finished generating code
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\gco
copying build\lib.win-amd64-3.8\gco\cgco.cpp -> build\bdist.win-amd64\egg\gco
copying build\lib.win-amd64-3.8\gco\cgco.h -> build\bdist.win-amd64\egg\gco
copying build\lib.win-amd64-3.8\gco\cgco.py -> build\bdist.win-amd64\egg\gco
copying build\lib.win-amd64-3.8\gco\libcgco.cp38-win_amd64.exp -> build\bdist.win-amd64\egg\gco
copying build\lib.win-amd64-3.8\gco\libcgco.cp38-win_amd64.lib -> build\bdist.win-amd64\egg\gco
copying build\lib.win-amd64-3.8\gco\libcgco.cp38-win_amd64.pyd -> build\bdist.win-amd64\egg\gco
copying build\lib.win-amd64-3.8\gco\pygco.py -> build\bdist.win-amd64\egg\gco
copying build\lib.win-amd64-3.8\gco\__init__.py -> build\bdist.win-amd64\egg\gco
byte-compiling build\bdist.win-amd64\egg\gco\cgco.py to cgco.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\gco\pygco.py to pygco.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\gco\__init__.py to __init__.cpython-38.pyc
creating stub loader for gco\libcgco.cp38-win_amd64.pyd
byte-compiling build\bdist.win-amd64\egg\gco\libcgco.py to libcgco.cpython-38.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying gco_wrapper.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying gco_wrapper.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying gco_wrapper.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying gco_wrapper.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying gco_wrapper.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying gco_wrapper.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
creating dist
creating 'dist\gco_wrapper-3.0.7-py3.8-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing gco_wrapper-3.0.7-py3.8-win-amd64.egg
creating c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages\gco_wrapper-3.0.7-py3.8-win-amd64.egg
Extracting gco_wrapper-3.0.7-py3.8-win-amd64.egg to c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages
Adding gco-wrapper 3.0.7 to easy-install.pth file

Installed c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages\gco_wrapper-3.0.7-py3.8-win-amd64.egg
Processing dependencies for gco-wrapper==3.0.7
Searching for urllib3==1.26.4
Best match: urllib3 1.26.4
Adding urllib3 1.26.4 to easy-install.pth file

Using c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages
Searching for matplotlib==3.4.2
Best match: matplotlib 3.4.2
Adding matplotlib 3.4.2 to easy-install.pth file

Using c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages
Searching for numpy==1.20.3
Best match: numpy 1.20.3
Adding numpy 1.20.3 to easy-install.pth file
Installing f2py-script.py script to C:\Users\marcu\AppData\Local\Programs\Python\Python38\Scripts
Installing f2py.exe script to C:\Users\marcu\AppData\Local\Programs\Python\Python38\Scripts

Using c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages
Searching for Cython==0.29.23
Best match: Cython 0.29.23
Adding Cython 0.29.23 to easy-install.pth file
Installing cygdb-script.py script to C:\Users\marcu\AppData\Local\Programs\Python\Python38\Scripts
Installing cygdb.exe script to C:\Users\marcu\AppData\Local\Programs\Python\Python38\Scripts
Installing cython-script.py script to C:\Users\marcu\AppData\Local\Programs\Python\Python38\Scripts
Installing cython.exe script to C:\Users\marcu\AppData\Local\Programs\Python\Python38\Scripts
Installing cythonize-script.py script to C:\Users\marcu\AppData\Local\Programs\Python\Python38\Scripts
Installing cythonize.exe script to C:\Users\marcu\AppData\Local\Programs\Python\Python38\Scripts

Using c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages
Searching for kiwisolver==1.3.1
Best match: kiwisolver 1.3.1
Adding kiwisolver 1.3.1 to easy-install.pth file

Using c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages
Searching for pyparsing==2.4.7
Best match: pyparsing 2.4.7
Adding pyparsing 2.4.7 to easy-install.pth file

Using c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages
Searching for Pillow==8.2.0
Best match: Pillow 8.2.0
Adding Pillow 8.2.0 to easy-install.pth file

Using c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages
Searching for python-dateutil==2.8.1
Best match: python-dateutil 2.8.1
Adding python-dateutil 2.8.1 to easy-install.pth file

Using c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages
Searching for six==1.16.0
Best match: six 1.16.0
Adding six 1.16.0 to easy-install.pth file

Using c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages
Finished processing dependencies for gco-wrapper==3.0.7

E:\Code\pyGCO>pip install gco-wrapper
Requirement already satisfied: gco-wrapper in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages\gco_wrapper-3.0.7-py3.8-win-amd64.egg (3.0.7)
Requirement already satisfied: Cython>=0.23.1 in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages (from gco-wrapper) (0.29.23)
Requirement already satisfied: numpy>=1.8.2 in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages (from gco-wrapper) (1.20.3)
Requirement already satisfied: matplotlib>=1.3.1 in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages (from gco-wrapper) (3.4.2)
Requirement already satisfied: urllib3 in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages (from gco-wrapper) (1.26.4)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages (from matplotlib>=1.3.1->gco-wrapper) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages (from matplotlib>=1.3.1->gco-wrapper) (2.8.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages (from matplotlib>=1.3.1->gco-wrapper) (8.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages (from matplotlib>=1.3.1->gco-wrapper) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages (from matplotlib>=1.3.1->gco-wrapper) (1.3.1)
Requirement already satisfied: six in c:\users\marcu\appdata\local\programs\python\python38\lib\site-packages (from cycler>=0.10->matplotlib>=1.3.1->gco-wrapper) (1.16.0)

E:\Code\pyGCO>python test_examples.py
Traceback (most recent call last):
  File "E:\Code\pyGCO\gco\__init__.py", line 5, in <module>
    from pygco import *  # noqa: F401 F403
ModuleNotFoundError: No module named 'pygco'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Code\pyGCO\gco\pygco.py", line 7, in <module>
    from cgco import _cgco, _SMOOTH_COST_FN
ModuleNotFoundError: No module named 'cgco'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_examples.py", line 10, in <module>
    import gco
  File "E:\Code\pyGCO\gco\__init__.py", line 7, in <module>
    from gco.pygco import *  # noqa: F401 F403
  File "E:\Code\pyGCO\gco\pygco.py", line 9, in <module>
    from .cgco import _cgco, _SMOOTH_COST_FN
  File "E:\Code\pyGCO\gco\cgco.py", line 12, in <module>
    assert len(LIST_LIBGCO) > 0, 'nothing found: %s' % repr(LIST_LIBGCO)
AssertionError: nothing found: []

E:\Code\pyGCO>
```

**Comment by Borda** [comment]
some seem to be similar to what I see with https://github.com/Borda/pyImSegm/pull/32
I have just uploaded the weels for most OS, mind try these? https://pypi.org/project/gco-wrapper/#files

**Comment by alexisrozhkov** [comment]
Same issue for me on Ubuntu 20.04:

> Traceback (most recent call last):
>   File ".../pyGCO/gco/__init__.py", line 5, in <module>
>     from pygco import *  # noqa: F401 F403
> ModuleNotFoundError: No module named 'pygco'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File ".../pyGCO/gco/pygco.py", line 7, in <module>
>     from cgco import _cgco, _SMOOTH_COST_FN
> ModuleNotFoundError: No module named 'cgco'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "test_examples.py", line 10, in <module>
>     import gco
>   File ".../pyGCO/gco/__init__.py", line 7, in <module>
>     from gco.pygco import *  # noqa: F401 F403
>   File ".../pyGCO/gco/pygco.py", line 9, in <module>
>     from .cgco import _cgco, _SMOOTH_COST_FN
>   File ".../pyGCO/gco/cgco.py", line 12, in <module>
>     assert len(LIST_LIBGCO) > 0, 'nothing found: %s' % repr(LIST_LIBGCO)
> AssertionError: nothing found: []

It seems that it's trying to load the built lib from `pyGCO/gco/libcgco.*` (which is not there), so I've manually copied `pyGCO/build/lib.linux-x86_64-3.8/gco/libcgco.cpython-38-x86_64-linux-gnu.so` there, and `test_examples.py `now seems to work fine.

**Comment by Borda** [comment]
Sounds like we would need to check out the extension amd/or overload the setuptools install class

**Comment by alexisrozhkov** [comment]
@Borda I debugged it a little bit and so far my impression is that the configuration in `setup.py` is fine, and it places the `*.so` file in the proper location (`.../lib/python3.8/site-packages/gco_wrapper-3.0.7-py3.8-linux-x86_64.egg/gco/libcgco.cpython-38-x86_64-linux-gnu.so` for me)

The root cause of the issue is the directory structure - when you call `python test_examples.py` from the repo root instead of importing the package from the path it was installed to, it is trying to load it from a local directory `{REPO_ROOT}/gco` (since the directory name matches the package name), and there you don't have a copy of the built lib. 

I was able to confirm it by renaming `{REPO_ROOT}/gco` to any other name - then proper library is loaded and `*.so` can be found as well. It seems that there are multiple ways to change the directory structure to prevent this behavior, so you can pick the one you find most appropriate :)

**Comment by Borda** [comment]
> The root cause of the issue is the directory structure - when you call `python test_examples.py` from the repo root instead of importing the package from the path it was installed to, it is trying to load it from a local directory `{REPO_ROOT}/gco` (since the directory name matches the package name), and there you don't have a copy of the built lib.

ok, that is quite expected, as in this case you are not importing the `gco` from site-packages but the local which does not have compiled lib inside (if you run install, then it is build folder)
