### ISSUE TITLE
PyPi package

### ISSUE THREAD

**Issue by Borda** [Borda/pyGCO#5]
The installation of `gco-wrapper==3.0.2c` repost following error even the package is installed properly...

```
(vEnv_test)borovji3@knuth:~/Desktop$ pip install 'gco-wrapper==3.0.2c'
/mnt/home.dokt/borovji3/Desktop/vEnv_test/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting gco-wrapper==3.0.2c
/mnt/home.dokt/borovji3/Desktop/vEnv_test/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached gco-wrapper-3.0.2rc0.tar.gz
Collecting Cython (from gco-wrapper==3.0.2c)
Collecting numpy (from gco-wrapper==3.0.2c)
  Downloading numpy-1.14.1.zip (4.9MB)
    100% |████████████████████████████████| 4.9MB 132kB/s 
Building wheels for collected packages: gco-wrapper, numpy
  Running setup.py bdist_wheel for gco-wrapper
  Complete output from command /mnt/home.dokt/borovji3/Desktop/vEnv_test/bin/python2 -c "import setuptools;__file__='/tmp/pip-build-CdmnZL/gco-wrapper/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp0WODkapip-wheel-:
  WARNING:root:Fail source download or unzip, so last VCS will be used.
  WARNING:root:Fail load requirements file, so using default ones.
  /mnt/home.dokt/borovji3/Desktop/vEnv_test/local/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '3.0.2c' to '3.0.2rc0'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/gco
  copying gco/__init__.py -> build/lib.linux-x86_64-2.7/gco
  copying gco/cgco.py -> build/lib.linux-x86_64-2.7/gco
  copying gco/pygco.py -> build/lib.linux-x86_64-2.7/gco
  running egg_info
  writing requirements to gco_wrapper.egg-info/requires.txt
  writing gco_wrapper.egg-info/PKG-INFO
  writing top-level names to gco_wrapper.egg-info/top_level.txt
  writing dependency_links to gco_wrapper.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'gco_wrapper.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'requirements.txt'
  writing manifest file 'gco_wrapper.egg-info/SOURCES.txt'
  copying gco/cgco.cpp -> build/lib.linux-x86_64-2.7/gco
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-CdmnZL/gco-wrapper/setup.py", line 137, in <module>
      'Programming Language :: Python :: 3.6',
    File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/mnt/home.dokt/borovji3/Desktop/vEnv_test/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 175, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-CdmnZL/gco-wrapper/setup.py", line 50, in run
      import numpy
  ImportError: No module named numpy
  
  ----------------------------------------
  Failed building wheel for gco-wrapper
  Running setup.py bdist_wheel for numpy
```

for configuration:

```
Cython==0.27.3
gco-wrapper==3.0.2rc0
numpy==1.14.1
wheel==0.24.0
```

**Comment by smidm** [comment]
https://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py
